#
# Makefile for Phoenix-RTOS loader (ARMv7M HAL stm32)
#
# Copyright 2021 Phoenix Systems
#
# %LICENSE%
#

include hal/armv8m/stm32/u5/Makefile
CFLAGS += -I../plo/hal/armv8m/stm32/u5
OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/stm32/, hal.o)
